### ISSUE TITLE
SeichiAssist銀行

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssistBank#1]
SeichiAssist銀行のシステムでお願いしたいです！もし仕様で不明点がありましたらメンション付きでここに書いていただけるとありがたいです！

()内のコマンドはおまけなので実装方法は任せます！

仕様:
SeichiAssist銀行の残高は全サーバーで共通(DBで管理)。
サーバーごとにユーザーの残高が分かれており、これはXConomy側で管理されている。XConomyの残高を管理する場合は、Vaultを経由する方が望ましい(XConomyから経済プラグインを変更する場合に使いまわせる)。

動作仕様:
・SeichiAssist銀行でユーザーごとにそれぞれの所有残高を記録。
・コマンド、もしくは棒メニューで所有残高を確認できる。(/seichiwallet)
・入金があった場合、Vaultを経由してXConomyで管理されているユーザーのアカウント残高を確認、足りる場合はVaultで残高を減らしてから銀行の残高に記録。(/seichideposit 1000)
・出金があった場合、SeichiAssist銀行のユーザーの所有残高を確認、足りる場合は銀行の残高を減らしてからVault経由でサーバーないのXConomy残高を増やす。(/seichiwithdraw 1000)

おまけ:
・サーバーを介さず、SeichiAssist銀行だけでユーザー間のお金のやり取りができると嬉しい。(/seichipay unchama 500 )

from: @Megumiso 
#admin-developer 2021/3/2
https://discord.com/channels/288275544234131456/288536178419040260/815962148152541184

**Comment by kory33** [comment]
(真面目な話をすると、これが今後完全にSeichiAssistと独立した機能になるかというのはちょっと気になりますね、このような機能が必要になった背景はどのようなものでしょうか？)

仕様についてですが、

> サーバーごとにユーザーの残高が分かれており

というのは普通に不便ではないでしょうか？すぐに思いつく実装ですと、例えば以下のような感じにできます：

 - プレーヤーがサーバーに参加したときにデータベース上の残高をXConomyに流し込む(上書き)
 - プレーヤーがサーバーに参加している状態に定期的に、そして退出時にXConomyでの残高をデータベース上に記録する

このような実装では、サーバーごとに残高を分ける必要が無く、XConomyの残高が全サーバーで"同期"されるようになります。この実装と求めるユースケースの間に何かズレはありますでしょうか？(もしかして、XConomyがすでに複数サーバーに入っていてこれがマズいとかがありますか？)

**Comment by Lucky3028** [comment]
すみません、今気が付きました、すみません...。
アイデア会議で別チケットで議論された結果、アルカディアだけにTownyを実装して本実装ということになりましたので、こちらのアイデアは不要になりました。

**Comment by Lucky3028** [comment]
すみません、すみません....
